### ISSUE TITLE
Gracefully deal with LIBFMT exception

### ISSUE THREAD

**Issue by strasdat** [farm-ng/farm-ng-core#116]
Currently, any format error such as ``FMT("arg1: {}, arg2:P{}", 5);`` will (most likely) crash the program. This is in most cases not desired. It will turn a minor documentation error into program abortion.

Proposal:
 - Log a warning with the raw format string e.g. "arg1: {}, arg2:P{}" plus the exception message and then continue execution as normal.
 
 Alternative:
  - Re-enable compile time fmt string parsing,. However this might involve sig. engineering work and also increase compile time.

**Comment by wylderkeane** [comment]
+1 to re-enabling compile time fmt string parsing unless it slows down the build significantly.

**Comment by strasdat** [comment]
this is done (not sure when it was completed though): https://github.com/farm-ng/farm-ng-core/blob/1724b98e6c1a755b3c9990ad321aaae729054bad/cpp/farm_ng/core/logging/format.h#L83

**Comment by strasdat** [comment]
Not done actually, doh...

**Comment by strasdat** [comment]
https://github.com/farm-ng/farm-ng-core/pull/255
