### ISSUE TITLE
[Feature] Merge boilerplate `get_event` and `read_message` 

### ISSUE THREAD

**Issue by edgarriba** [farm-ng/farm-ng-core#45]
@Hackerman342 @ethanrublee an improvement here is to merge `get_event` and `read_message` since we use all the time together. For testing and some internal use cases is good but better coupled for a more user friendly api
```python
def read_uri_message(self, uri: uri_pb2.Uri, event_id: int) -> Any:
    # get the event and offset
    event: event_pb2.Event
    offset: int
    event, offset = self.get_event(uri, current_event)

    # seek and parse the message
    return self.read_message(event, offset)
```

maybe `read_message` should be renamed to `parse_message` and `read_message` recive the uri and event_id

_Originally posted by @edgarriba in https://github.com/farm-ng/amiga-brain-api/pull/31#discussion_r1025117076_

**Comment by ethanrublee** [comment]
The c++ side I do like how the event is wrapped in a helper class that has
the read function similar to an itetator, this allows for just in time
reading and performing range based algorithms on the event.

I would suggest we do something similar in python, and also port the time
ordered zipping from c++ in the same feature as it’s a prime use case
